services:
    php:
        build: .
        restart: always
        container_name: prueba-tecnica-backend
        volumes:
            - ./app:/var/www/html
        networks:
            - prueba-tecnica-network
    nginx:
        image: nginx:1.27.4-alpine
        container_name: prueba-tecnica-server
        restart: always
        ports:
            - ${PORT:-80}:80
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ./app:/var/www/html
        networks:
            - prueba-tecnica-network
        depends_on:
            - php
            - db
    db:
        image: mysql:9.2.0
        restart: always
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=false
            - MYSQL_DATABASE=$DB_DATABASE
            - MYSQL_USER=$DB_USER
            - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/MYSQL_ROOT_PASSWORD
            - MYSQL_PASSWORD_FILE=/run/secrets/MYSQL_PASSWORD
        secrets:
            - MYSQL_ROOT_PASSWORD
            - MYSQL_PASSWORD
secrets:
    MYSQL_ROOT_PASSWORD:
        environment: "DB_ROOT_PASSWORD"
    MYSQL_PASSWORD:
        environment: "DB_PASSWORD"
networks:
    prueba-tecnica-network:
        driver: bridge